### ISSUE TITLE
Error handling in .catch()

### ISSUE THREAD

**Issue by stakira** [aimingoo/Promise#1]
First of all, thanks for this wonderful library.
It seems if error() is called in .catch(), nothing will be displayed. This is probably due to the fact that Lua will not display error() called in a coroutine.
Could you please see if it's possible to catch this error and display it out?
Thanks.

**Comment by aimingoo** [comment]
pls catch again.  ^^.

``` lua
Promise = require("Promise");
err1 = function() error("error-1") end;
err2 = function() error("error-2") end; 

Promise.resolve()
    :andThen(err1)   -- throw a error
    :catch(err2)  -- catch err1, but throw err2
    :catch(function(msg)
        print(msg .. '\n' .. debug.traceback());  -- catch err2, and print trace stack
    end);


----- console output
-- stdin:1: error-2
-- stack traceback:
--    stdin:1: in function <stdin:1>
-- ...
```

**Comment by stakira** [comment]
Thank you very much for the explanation.
