### ISSUE TITLE
some error about Promise.all

### ISSUE THREAD

**Issue by fgfg163** [aimingoo/Promise#2]
In es2015, 
`
Promise.all([1, 2, 3, 4, 5]).then(console.log)
`
print "[1,2,3,4,5]"

but in this lua Promise
`
Promise.all({1, 2, 3, 4, 5}).andThen(print)
`
do nothing.

**Comment by fgfg163** [comment]
ho, it must use ":", not "." before andThen
this right `Promise.all({1, 2, 3, 4, 5}):andThen(print)`

**Comment by aimingoo** [comment]
Ya. 👍
